[Variables]
; Example for empty rows:
; gameCover = "resources/images/placeholder.png" (placeholder text)
; gameCover = "resources/images/emptySlot.png" (transparent picture)
; gameTarget = ""

gameCover01 = "resources/images/placeholder.png"
gameTarget01 = ""

gameCover02 = "resources/images/placeholder.png"
gameTarget02 = ""

gameCover03 = "resources/images/placeholder.png"
gameTarget03 = ""

gameCover04 = "resources/images/placeholder.png"
gameTarget04 = ""

gameCover05 = "resources/images/placeholder.png"
gameTarget05 = ""

gameCover06 = "resources/images/placeholder.png"
gameTarget06 = ""

gameCover07 = "resources/images/placeholder.png"
gameTarget07 = ""

gameCover08 = "resources/images/placeholder.png"
gameTarget08 = ""

gameCover09 = "resources/images/placeholder.png"
gameTarget09 = ""

gameCover10 = "resources/images/placeholder.png"
gameTarget10 = ""