[Variables]
; Example for empty rows:
; gameCover = "resources/images/emptySlot.png" (placeholder text)
; gameCover = "resources/images/emptySlot.png" (transparent picture)
; gameTarget = ""

; for (var i = 1; i < 50; i++) {
; 	const meterNumber = i >= 9 ? i + 1 : '0' + (i + 1);
;
; 	console.log(`
; gameCover${meterNumber} = "resources/images/emptySlot.png"
; gameTarget${meterNumber} = ""
; `);
; }

gameCover01 = "Z:\Pictures\Misc\Covers\Steam\logos\white\Fallout 4.png"
gameTarget01 = "Z:\Games\Single Player\Fallout 4\f4se_loader.exe"

gameCover02 = "Z:\Pictures\Misc\Covers\Steam\logos\white\Far Cry 3.png"
gameTarget02 = "Z:\Games\Single Player\Far Cry 3\bin\farcry3_d3d11.exe"

gameCover03 = "Z:\Pictures\Misc\Covers\Steam\logos\white\Recettear.png"
gameTarget03 = "Z:\Games\Single Player\_casual\Recettear - An Item Shop's Tale\recettear.exe"

gameCover04 = "Z:\Pictures\Misc\Covers\Steam\logos\white\Devil May Cry.png"
gameTarget04 = "Z:\Games\Single Player\Devil May Cry HD Collection\dmcLauncher.exe"

gameCover05 = "Z:\Pictures\Misc\Covers\Steam\logos\white\DOOM.png"
gameTarget05 = "Z:\Games\Single Player\Doom 2016\DOOMx64.exe"

gameCover06 = "Z:\Pictures\Misc\Covers\Steam\logos\white\Crash Bandicoot.png"
gameTarget06 = "Z:\Games\Single Player\Crash Bandicoot N Sane Trilogy\CrashBandicootNSaneTrilogy.exe"

gameCover07 = "Z:\Pictures\Misc\Covers\Steam\logos\white\Witcher 3.png"
gameTarget07 = "Z:\Games\Adri\The Witcher 3 - Wild Hunt\bin\x64\witcher3.exe"

gameCover08 = "Z:\Pictures\Misc\Covers\Steam\logos\white\Ni no Kuni II.png"
gameTarget08 = "Z:\Games\Adri\Ni no Kuni II Revenant Kingdom\Nino2.exe"

gameCover09 = "resources/images/emptySlot.png"
gameTarget09 = ""

gameCover10 = "resources/images/emptySlot.png"
gameTarget10 = ""

gameCover11 = "resources/images/emptySlot.png"
gameTarget11 = ""

gameCover12 = "resources/images/emptySlot.png"
gameTarget12 = ""

gameCover13 = "resources/images/emptySlot.png"
gameTarget13 = ""

gameCover14 = "resources/images/emptySlot.png"
gameTarget14 = ""

gameCover15 = "resources/images/emptySlot.png"
gameTarget15 = ""

gameCover16 = "resources/images/emptySlot.png"
gameTarget16 = ""

gameCover17 = "resources/images/emptySlot.png"
gameTarget17 = ""

gameCover18 = "resources/images/emptySlot.png"
gameTarget18 = ""

gameCover19 = "resources/images/emptySlot.png"
gameTarget19 = ""

gameCover20 = "resources/images/emptySlot.png"
gameTarget20 = ""

gameCover21 = "resources/images/emptySlot.png"
gameTarget21 = ""

gameCover22 = "resources/images/emptySlot.png"
gameTarget22 = ""

gameCover23 = "resources/images/emptySlot.png"
gameTarget23 = ""

gameCover24 = "resources/images/emptySlot.png"
gameTarget24 = ""

gameCover25 = "resources/images/emptySlot.png"
gameTarget25 = ""

gameCover26 = "resources/images/emptySlot.png"
gameTarget26 = ""

gameCover27 = "Z:\Pictures\Misc\Covers\Steam\logos\white\Minecraft.png"
gameTarget27 = "%appdata%\.minecraft\MinecraftLauncher.exe"

gameCover28 = "Z:\Pictures\Misc\Covers\Steam\logos\white\Blade & Soul (clean).png"
gameTarget28 = "C:\Program Files (x86)\NCWest\NCLauncher\NCLauncher.exe" /LauncherID:"NCWest" /CompanyID:"12" /GameID:"BnS" /LUpdateAddr:"updater.nclauncher.ncsoft.com"

gameCover29 = "Z:\Pictures\Misc\Covers\Steam\logos\white\Elsword.png"
gameTarget29 = "Z:\Games\Masive Multiplayer Online\Elsword NA\elsword.exe"

gameCover30 = "Z:\Pictures\Misc\Covers\Steam\logos\white\osu!.png"
gameTarget30 = "Z:\Games\Single Player\osu!\osu!.exe"

gameCover31 = "resources/images/emptySlot.png"
gameTarget31 = ""

gameCover32 = "resources/images/emptySlot.png"
gameTarget32 = ""

gameCover33 = "resources/images/emptySlot.png"
gameTarget33 = ""

gameCover34 = "resources/images/emptySlot.png"
gameTarget34 = ""

gameCover35 = "resources/images/emptySlot.png"
gameTarget35 = ""

gameCover36 = "resources/images/emptySlot.png"
gameTarget36 = ""

gameCover37 = "resources/images/emptySlot.png"
gameTarget37 = ""

gameCover38 = "resources/images/emptySlot.png"
gameTarget38 = ""

gameCover39 = "resources/images/emptySlot.png"
gameTarget39 = ""

gameCover40 = "resources/images/emptySlot.png"
gameTarget40 = ""

gameCover41 = "resources/images/emptySlot.png"
gameTarget41 = ""

gameCover42 = "resources/images/emptySlot.png"
gameTarget42 = ""

gameCover43 = "resources/images/emptySlot.png"
gameTarget43 = ""

gameCover44 = "resources/images/emptySlot.png"
gameTarget44 = ""

gameCover45 = "resources/images/emptySlot.png"
gameTarget45 = ""

gameCover46 = "resources/images/emptySlot.png"
gameTarget46 = ""

gameCover47 = "resources/images/emptySlot.png"
gameTarget47 = ""

gameCover48 = "resources/images/emptySlot.png"
gameTarget48 = ""

gameCover49 = "resources/images/emptySlot.png"
gameTarget49 = ""

gameCover50 = "resources/images/emptySlot.png"
gameTarget50 = ""