[Rainmeter]
Update=1000
DynamicWindowSize=1

[Variables]
DigitRegex="^([0-9]{1})([0-9]{1})([0-9]{1})([0-9]{1})$"
DigitHeight=19
DigitWidth=13
SeparatorWidth=7
ImageHeight=19
ImageSpacing=-2
ImagePath=sharp

[MeasureTime]
Measure=Time
Format=%H%M

[MeasureHourDec]
Measure=String
String=[MeasureTime]
DynamicVariables=1
RegExpSubstitute=1
Substitute="#DigitRegex#":"\1"

[MeasureHourUnit]
Measure=String
String=[MeasureTime]
DynamicVariables=1
RegExpSubstitute=1
Substitute="#DigitRegex#":"\2"

[MeasureMinuteDec]
Measure=String
String=[MeasureTime]
DynamicVariables=1
RegExpSubstitute=1
Substitute="#DigitRegex#":"\3"

[MeasureMinuteUnit]
Measure=String
String=[MeasureTime]
DynamicVariables=1
RegExpSubstitute=1
Substitute="#DigitRegex#":"\4"

; [ImageBackground]
; Meter=Image
; ImageName=bg.png
; W=51
; H=#DigitHeight#

[ImageHourDec]
Meter=Image
MeasureName=MeasureHourDec
ImagePath=#ImagePath#
W=#DigitWidth#
H=#DigitHeight#

[ImageHourUnit]
Meter=Image
MeasureName=MeasureHourUnit
ImagePath=#ImagePath#
W=#DigitWidth#
H=#DigitHeight#
X=#ImageSpacing#R

[ImageHourSeparator]
Meter=Image
ImageName=separator.png
ImagePath=#ImagePath#
W=#SeparatorWidth#
H=#ImageHeight#
X=#ImageSpacing#R

[ImageMinuteDec]
Meter=Image
MeasureName=MeasureMinuteDec
ImagePath=#ImagePath#
W=#DigitWidth#
H=#DigitHeight#
X=#ImageSpacing#R

[ImageMinuteUnit]
Meter=Image
MeasureName=MeasureMinuteUnit
ImagePath=#ImagePath#
W=#DigitWidth#
H=#DigitHeight#
X=#ImageSpacing#R
