[Variables]

[UsageCircle]
AntiAlias = 1
Solid = 1
LineStart = 15
LineLength = 18
StartAngle = (Rad(270))
RotationAngle = (Rad(360))

[UsageCirclePercent]
AntiAlias = 1
FontSize = 8
FontColor = #cWhite#
StringStyle = Bold
StringAlign = CenterCenter
;Text = 100%
Text = %1%

[UsageCircleLabel]
AntiAlias = 1
FontSize = 14
FontColor = #cWhite#
;StringStyle = Bold

[UsageValueLabel]
AntiAlias = 1
FontSize = 10
FontColor = #cWhite#
StringStyle = Bold
StringAlign = CenterCenter
Text = %1%

[AliasedText]
AntiAlias = 1