[Variables]
FontEffectColor = 0, 0, 0, 51
FontFace = century
FontBoldeness = Bold
FontSize = 12

[OutlinedText]
FontFace = #FontFace#
FontColor = 255, 255, 255, 255
FontSize = #FontSize#
FontEffectColor = #FontEffectColor#
StringEffect = Border

StringStyle = #FontBoldeness#
AntiAlias = 1


[ShadowText]
FontFace = century
FontColor = 0, 0, 0, 51
FontSize = #FontSize#

StringStyle = #FontBoldeness#
AntiAlias = 1