[Rainmeter]
Update = -1
ContextTitle  = Profile
ContextAction  = [steam://url/SteamIDMyProfile]
ContextTitle2 = Friends
ContextAction2 = [steam://open/friends]
ContextTitle3 = Inventory
ContextAction3 = [steam://open/inventory]
ContextTitle4 = Library
ContextAction4 = [steam://open/games]
ContextTitle5 = ----
ContextTitle6 = Store
ContextAction6 = [steam://url/storefrontpage]
ContextTitle7 = Wishlist
ContextAction7 = [steam://url/UserWishlist]
ContextTitle8 = Downloads
ContextAction8 = [steam://nav/downloads]
ContextTitle9 = ----
ContextTitle10 = Skin settings
ContextAction10 = [!SkinMenu]
OnRefreshAction = [!Hide "MetalTxus - Modular Game Launchers\Steam\Games list"]

;[Hotkey]
;Measure = Plugin
;Plugin = HotKey
;HotKey = #toggleHotKey#
;KeyDownAction = [!ZPosGroup "2" "SteamHotkeyToggle"]
;KeyUpAction = [!ZPosGroup "-2" "SteamHotkeyToggle"]
