[Variables]
AntiAlias = 0
; FontEffectColor = 0, 0, 0
InlineSetting = Shadow | .5 | 0 | 1 | 0, 0, 0, 255
InlineSetting2 = Shadow | 0 | 0 | 2 | 0, 0, 0, 128
; InlineSetting  = Shadow | 0 | 2 | 0 | 0, 0, 0, 255
; InlineSetting2 = Shadow | 0 | -2 | 0 | 0, 0, 0, 255
; InlineSetting3 = Shadow | 0 | 0 | 2 | 0, 0, 0, 255
; InlineSetting4 = Shadow | 0 | 0 | -2 | 0, 0, 0, 255
; InlineSetting5 = Shadow | 0 | 2 | 2 | 0, 0, 0, 255
; InlineSetting6 = Shadow | 0 | -2 | 2 | 0, 0, 0, 255
; InlineSetting7 = Shadow | 0 | 2 | -2 | 0, 0, 0, 255
; InlineSetting8 = Shadow | 0 | -2 | -2 | 0, 0, 0, 255
StringAlign = RightTop
StringEffect = Border
TextY = 2