[Variables]
AntiAlias = 0
FontEffectColor = 0, 0, 0
FontWeight = 500
; InlineSetting  = Shadow | 0 | 0 | 0 | 0, 0, 0
; InlineSetting2 = Shadow | 0 | 0 | 0 | 0, 0, 0
; InlineSetting3 = Shadow | 0 | 0 | 0 | 0, 0, 0
; InlineSetting4 = Shadow | 0 | 0 | 0 | 0, 0, 0
; InlineSetting5 = Shadow | 0 | 0 | 0 | 0, 0, 0
; InlineSetting6 = Shadow | 0 | 0 | 0 | 0, 0, 0
; InlineSetting7 = Shadow | 0 | 0 | 0 | 0, 0, 0
; InlineSetting8 = Shadow | 0 | 0 | 0 | 0, 0, 0
StringAlign = LeftTop
StringEffect = Border
TextX = 2
TextY = 2