[Variables]

; General settings
steamURL          = http://steamcommunity.com/id/MetalTxus/games?tab=recent		\\Link to your profile here (Keep "/games?tab=recent" at the end of your profile)
hoverColor        = 255, 255, 255, 255
regularColor      = 200, 200, 200, 255
backgroundColor   = 16,   16,  16, 1

; PC horizontal variant settings
horizontalWidth   = 1920
horizontalRows    = 3
horizontalColumns = 10

; PC vertical variant settings
verticalHeight    = 1040
verticalRows      = 10
verticalColumns   = 3



; Fixed values (do not change)

: General
coverWidth = 460
coverHeight = 215

; Steam horizontal variant settings
steamHorizontalRows = 1
steamHorizontalColumns = 10

; Steam vertical variant settings
steamVerticalRows = 10
steamVerticalColumns = 1